name: Deploy Azure Bicep
// how to add secrets.SECRET_KEY in github repo settings
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - uses: actions/checkout@v4

      - name: List folder contents
        run: ls


      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Determine which parameter file to use
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PARAMS_FILE=main.prod.bicepparam" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=rgmyappprod " >> $GITHUB_ENV
          else
            echo "PARAMS_FILE=main.dev.bicepparam" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=rgmyappdev" >> $GITHUB_ENV
          fi

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./IaC/AzureBiceps/main.bicep
          parameters: ./IaC/AzureBiceps/${{ env.PARAMS_FILE }}